server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service       # T�n ??nh danh route
          uri: lb://auth-service # Load balance(lb) ??n service c� t�n "product-service" trong Eureka
          predicates:
            - Path=/api/v1/auth/**     # R??nh tuy?n request ??n microservice product-service khi c� URL b?t ??u b?ng /products/**.
          filters:
            - AddRequestHeader=X-Request-Foo, Bar  # Th�m header v�o request tr??c khi g?i downstream service(l� product-service)

        - id: user-service       # T�n ??nh danh route
          uri: lb://user-service # Load balance(lb) ??n service c� t�n "product-service" trong Eureka
          predicates:
            - Path=/api/v1/users/**     # R??nh tuy?n request ??n microservice product-service khi c� URL b?t ??u b?ng /products/**.
          filters:
            - AddRequestHeader=X-Request-Foo, Bar  # Th�m header v�o request tr??c khi g?i downstream service(l� product-service)


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #localhost
#    health-check:
#      enabled: true
#    instance:
#      prefer-ip-address: true

#C?u h�nh n�y ch? d�ng ?? API Gateway ??ng nh?p b?ng Google, kh�ng ph?i ?? b?o v? c�c API backend.
#security:
#  oauth2:
#    client:
#      registration:
#        google:
#          client-id: ${OAUTH2_GOOGLE_CLIENT_ID}       # L?y t? bi?n m�i tr??ng
#          client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
#          scope: profile, email                        # Quy?n truy c?p
#          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"  # URL callback sau ??ng nh?p
#      provider:
#        google:
#          authorization-uri: https://accounts.google.com/o/oauth2/auth  # Endpoint xin ph�p ??ng nh?p
#          token-uri: https://oauth2.googleapis.com/token                # Endpoint l?y token
#          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo  # Endpoint l?y th�ng tin user
